<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<AssemblyName>MSBuild.ExtensionPack.Security</AssemblyName>
		<AssemblyOriginatorKeyFile>D:\GitHub\MSBuildExtensionPack\Common\RamTunedMegaCode.public.snk</AssemblyOriginatorKeyFile>
		<Authors>John Merryweather Cooper,  Mike Fourie</Authors>
		<Company>Ram Tuned Mega Code</Company>
		<Copyright>Copyright (c) 2008-2025, John Merryweather Cooper.  All Rights Reserved.</Copyright>
		<DelaySign>True</DelaySign>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<IncludeSymbols>True</IncludeSymbols>
		<LangVersion>latest</LangVersion>
		<NuGetAuditMode>all</NuGetAuditMode>
		<Nullable>enable</Nullable>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/jmcooper176/MSBuildExtensionPack</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Product>MSBuild Extension Pack 6.0</Product>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/jmcooper176/MSBuildExtensionPack.git</RepositoryUrl>
		<RootNamespace>MSBuild.ExtensionPack.Security</RootNamespace>
		<SignAssembly>True</SignAssembly>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Title>MSBuild Extension Pack Security Classes</Title>
		<Version>6.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Base\Base.csproj" />
  </ItemGroup>

</Project>
