<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>MSBuild.ExtensionPack.Loggers</RootNamespace>
    <AssemblyName>MSBuild.ExtensionPack.Loggers</AssemblyName>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <AssemblyOriginatorKeyFile>D:\GitHub\MSBuildExtensionPack\Common\RamTunedMegaCode.public.snk</AssemblyOriginatorKeyFile>
    <Authors>John Merryweather Cooper, Mike Fourie</Authors>
    <Company>Ram Tuned Mega Code</Company>
    <Copyright>Copyright (c) 2008-2025, John Merryweather Cooper.  All Rights Reserved.</Copyright>
    <DelaySign>True</DelaySign>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeSymbols>True</IncludeSymbols>
    <NuGetAuditMode>all</NuGetAuditMode>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/jmcooper176/MSBuildExtensionPack</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Product>MSBuild Extension Pack 6.0</Product>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jmcooper176/MSBuildExtensionPack.git</RepositoryUrl>
    <SignAssembly>True</SignAssembly>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Title>MSBuild Extension Pack Loggers SecureFileLogger</Title>
    <Version>6.0.0</Version>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <WarningLevel>9999</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.47.1" />
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Json.More.Net" Version="2.1.2" />
    <PackageReference Include="JsonPointer.Net" Version="5.3.1" />
    <PackageReference Include="JsonSchema.Net" Version="7.3.4" />
    <PackageReference Include="Markdig.Signed" Version="0.41.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.8" />
    <PackageReference Include="Microsoft.Bcl.Cryptography" Version="9.0.8" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.14.8" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.74.1" />
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.5.2" />
    <PackageReference Include="System.DirectoryServices" Version="9.0.8" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.8" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
    <PackageReference Include="System.IO.Packaging" Version="9.0.8" />
    <PackageReference Include="System.IO.Ports" Version="9.0.8" />
    <PackageReference Include="System.Management" Version="9.0.7" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="9.0.8" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
    <PackageReference Include="System.Reflection.DispatchProxy" Version="4.8.2" />
    <PackageReference Include="System.Runtime.Caching" Version="9.0.8" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.8" />
    <PackageReference Include="System.Security.Permissions" Version="9.0.8" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="9.0.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.8" />
    <PackageReference Include="System.Speech" Version="9.0.8" />
    <PackageReference Include="System.Threading.AccessControl" Version="9.0.8" />
    <PackageReference Include="System.Web.Services.Description" Version="8.1.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="XmlSamples\SecureFileLogger.proj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Base\Base.csproj" />
  </ItemGroup>
</Project>