<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="lock-open.png" />
    <Content Include="lock.ico" />
    <Content Include="lock.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="GetPasswordForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="GetPasswordForm.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

</Project>
